### ISSUE TITLE
Refactor Contexts

### ISSUE THREAD

**Issue by taitfuller** [SE750-DART/nerds-oppose-society#131]
The [Context](https://reactjs.org/docs/context.html)'s used in the frontend are quite cluttered and would benefit from some refactoring. I propose the following changes to remedy this and provide better maintainability and testability throughout the frontend.

### Proposed Changes

- [X]  **Rename files**
  - Example: `src/providers/ContextProviders/PlayersContextProvider.tsx` → `src/contexts/players.ts`.
  - See #127.
- [X] **Cleanup**
  - An initial refactor to cleanup interface exposed by each context and their internals
    - Each context would export a custom hook (i.e. `usePlayers()`) that would internally call [`useContext()`](https://reactjs.org/docs/hooks-reference.html#usecontext):
      - This means that the Context object (returned by [`React.createContext()`](https://reactjs.org/docs/context.html#reactcreatecontext) no longer needs to be exported - helping to hide context internals
      - The value of the Context object will be initialised to be `undefined` - this goes hand-in-hand with the custom hook by ensuring that it is used within the scope of the respective [`Provider`](https://reactjs.org/docs/context.html#contextprovider). The hook will throw an error when used outside a provider. This improves developer experience by making behaviour of the contexts more predictable.
    - The internals of the hooks updated to use memoization with [`useCallback()`](https://reactjs.org/docs/hooks-reference.html#usecallback) and [`useMemo()`](https://reactjs.org/docs/hooks-reference.html#usememo) to reduce unnecessary re-renders.
  - See #132.
- [ ] **Convert internal state to [`useReducer()`](https://reactjs.org/docs/hooks-reference.html#usereducer)**
  - This change would offer a number of improvements for each context:
    - It should largely remove the various functions returned by each context replaced by a single `dispatch()`.
    - It would also make testing state transitions easier through the `reducer()` function defined for each context.
  - Breakdown:
    - [x] Refactor `players` context. See #142.
    - [x] Refactor `punchlines` context. See #140.
    - [ ] Refactor `round` context. See #144.
    - [x] Remove `useCrud` hook. See #143.

### Future

While these changes will be a great improvement when complete, long-term I think it might be worth switching to [Redux](https://redux-toolkit.js.org) to replace these contexts.

Converting the contexts to [`useReducer()`](https://reactjs.org/docs/hooks-reference.html#usereducer) internally will be a great stepping stone for an eventual switch to Redux, as the rest of the application will already be configured to use `dispatch()` for state changes.
